# Generated by Django 5.0.3 on 2024-03-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_remove_categoria_slug_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
