# Generated by Django 5.0.3 on 2024-03-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
