# Generated by Django 5.0.3 on 2024-03-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajecontacto',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
