# Generated by Django 5.0.3 on 2024-03-12 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarioperfil',
            old_name='nombre',
            new_name='user',
        ),
    ]
